name: Step 4

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  required_issue_comment_keywords:
    name: Check issue comment text for required keyword
    runs-on: ubuntu-latest
    steps:
      - name: Check for professortocat reference
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: 'professortocat'
          case-sensitive: false
          minimum-occurrences: 1
      - name: Check for codespace reference
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: 'codespace'
          case-sensitive: false
          minimum-occurrences: 1

  find_exercise:
    needs: [required_issue_comment_keywords]
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.5.0

  post_review_content:
    name: Post review content
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$REVIEW_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.5.0
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}

  disable_workflow:
    name: Disable this workflow
    needs: [find_exercise, post_review_content]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable current workflow
        run: gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
